// Copies the app's design tokens into this repo as a generated file.
// The site has no runtime dependency on the app: this runs on demand only.
//   node scripts/sync-tokens.mjs [path/to/variables.css]
// Default source: ../edu-assets/frontend/src/styles/base/variables.css
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(
  root,
  process.argv[2] ?? '../edu-assets/frontend/src/styles/base/variables.css',
);
const target = resolve(root, 'src/styles/base/tokens.css');

const css = readFileSync(source, 'utf8');
if (!css.includes(':root')) throw new Error(`No :root block found in ${source}`);

const header = `/* GENERATED by scripts/sync-tokens.mjs from the eduAssets app (variables.css).
   Do not edit by hand: change the app tokens and run \`npm run sync:tokens\`. */\n\n`;
writeFileSync(target, header + css);
console.log(`tokens synced: ${source} -> ${target}`);
